<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<DefaultItemExcludes>$(DefaultItemExcludes);libs/**;tests/**</DefaultItemExcludes>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>12</LangVersion>
		<RootNamespace>Pidamg.KeePass.Kdbx</RootNamespace>
		<AssemblyName>Pidamg.KeePass.Kdbx</AssemblyName>

		<!-- NuGet / Package Registry -->
		<PackageId>Pidamg.KeePass.Kdbx</PackageId>
		<IsPackable>true</IsPackable>
		<Version>0.0.0-dev</Version>
		<Authors>pidamg</Authors>
		<Description>Bibliothèque .NET pour lire et écrire les fichiers de mots de passe KeePass (.kdbx).</Description>
		<PackageTags>keepass;kdbx;password;vault</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/pidamg/lib-dotnet-keepass</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/pidamg/lib-dotnet-keepass</PackageProjectUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
	</PropertyGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
	</ItemGroup>
</Project>
